kconfig: add options for maximum PSK-ID and PSK lengths
golioth/golioth-zephyr-sdk pull request #394
Opened 2023-06-13 10:06 UTC by mniestroj

PSK-ID length was always hardcoded to maximum 64 characters. As a result
long project names with long PSK-IDs (due to
`long-device-id@long-project-name` PSK-ID format) would not be supported.

PSK had the same issue, but only when used with NCS.

Introduce options for both, PSK-ID and PSK, so that long credentials can be
supported without changing SDK codebase.

2023-06-13 10:21 UTC, mniestroj commented
FYI: @danyocom

2023-06-14 19:47 UTC, sam-golioth commented
@ChrisGammell ran into the same problem and it took him a while to figure out what the issue was. It looks like it wasn't immediately obvious to @danyocom either. @mniestroj can we also add an error message to the console if the length exceeds the configured value? That way it should be pretty straightforward for users who encounter this issue to determine what caused it and how to fix it.

2023-06-20 20:46 UTC, szczys submitted a review, later dismissed
LGTM!

2023-06-20 22:20 UTC, szczys reviewed
When testing `samples/settings` on esp32 I am unable to store setting;

```
uart:~$ settings set golioth/psk 12345
Setting golioth/psk to 12345
Failed to save setting golioth/psk:12345
```

2023-06-20 22:20 UTC, szczys commented on net/golioth/Kconfig
> +if GOLIOTH_SYSTEM_SETTINGS
I like that there's an ASSERT to detect values that are too long:
```
/home/mike/golioth-zephyr-workspace/modules/lib/golioth/net/golioth/system_client.c:38:1: error: static assertion failed: "PSK exceeds mbedTLS configured maximum PSK length"
   38 | BUILD_ASSERT(sizeof(TLS_PSK) - 1 <= CONFIG_MBEDTLS_PSK_MAX_LEN,
      | ^~~~~~~~~~~~
```

However, selecting `GOLIOTH_SYSTEM_SETTINGS` means compiled-in credentials can't access the new length settings.

```
config GOLIOTH_SYSTEM_CLIENT_PSK_ID
	string "PSK ID"
	depends on !GOLIOTH_SYSTEM_SETTINGS
```

2023-06-20 22:44 UTC, szczys commented
> @mniestroj can we also add an error message to the console if the length exceeds the configured value? That way it should be pretty straightforward for users who encounter this issue to determine what caused it and how to fix it.

I agree with this. I tested a psk-id that was 148 chars long with the limit set to 128. The credential save succeeded without error messages but the device failed to connect.

2023-06-20 22:53 UTC, szczys commented on net/golioth/Kconfig
> +config GOLIOTH_SYSTEM_CLIENT_PSK_MAX_LEN
I am unable to get this to work when my PSK is longer than 32 characters.

2023-06-23 19:27 UTC, sam-golioth requested changes
Looks good once we add the error message for exceeding the configured length

2023-07-13 19:49 UTC, sam-golioth approved these changes

2023-07-13 19:58 UTC, merged