bump Zephyr to 3.5.0-rc3 and NCS to tip of main (2.5.0-rc1+)
golioth/golioth-zephyr-sdk pull request #438
Opened 2023-10-17 12:31 UTC by mniestroj

Bump Zephyr to latest release candidate to test it before final 3.5.0
release.

Bump NCS to tip of main (slightly newer than 2.5.0-rc1 tag), to find
potential nRF91* platform regressions.

Replace `rand32.h` with `random.h` to suppress header deprecation warning. Add
a workaround for older Zephyr versions (like the one used by NCS fork) by
providing `random.h` just for internal Golioth SDK library visibility.

2023-10-17 20:40 UTC, sam-golioth commented
Looks like the [build test failed](https://github.com/golioth/golioth-zephyr-sdk/actions/runs/6547204552?pr=438), because the runner ran out of disk space. I hit the same error in the CP SDK, and you should be able to fix it by parallelizing the build similar to https://github.com/golioth/golioth-firmware-sdk/commit/5eb86b75ba9e9561d6fe013ef69b793eccf5301d

2023-10-17 20:41 UTC, sam-golioth requested changes
Looks like the [build test failed](https://github.com/golioth/golioth-zephyr-sdk/actions/runs/6547204552?pr=438), because the runner ran out of disk space. I hit the same error in the CP SDK, and you should be able to fix it by parallelizing the build similar to https://github.com/golioth/golioth-firmware-sdk/commit/5eb86b75ba9e9561d6fe013ef69b793eccf5301d

2023-10-19 13:44 UTC, mniestroj commented
> Looks like the [build test failed](https://github.com/golioth/golioth-zephyr-sdk/actions/runs/6547204552?pr=438), because the runner ran out of disk space. I hit the same error in the CP SDK, and you should be able to fix it by parallelizing the build similar to [golioth/golioth-firmware-sdk@5eb86b7](https://github.com/golioth/golioth-firmware-sdk/commit/5eb86b75ba9e9561d6fe013ef69b793eccf5301d)

Proposed solution (https://github.com/golioth/golioth-zephyr-sdk/pull/439) is slightly different, much smaller in boilerplate code size, but seems like a perfect fit for what we have now. This will give some input for comparison with the solution you proposed and implemented for CP SDK. Both are fine, maybe they can be combined together. My implementation was inspired by Zephyr CI matrix (but they use arbitrary number of matrix instances, which is then passed to twister, which decides by its own how to divide all test cases to be executed).

2023-10-19 14:44 UTC, mniestroj commented
@sam-golioth Do you have some idea about why `build` job is "Expected - Waiting for status to be reported"? It looks like a job that is the parent for 3 matrix jobs. Those 3 jobs are successful, but still, `build` is somehow pending. In case that is something new, I'll just investigate what the issue might be (I guess something in workflow specification which is not exactly what GitHub expects, or I just need close/reopen to workaround some corner case in GitHub CI).

2023-10-19 14:57 UTC, sam-golioth commented
> @sam-golioth Do you have some idea about why `build` job is "Expected - Waiting for status to be reported"?

I had marked the `build` job as a required check after it failed on this PR earlier. The reason is because when a runner runs out of disk space, the job is marked as "skipped" not "failed" and the PR UI treats skipped jobs like successful jobs (it still said "All checks have passed"), so it wasn't obvious that there was an issue. Marking it as required makes sure we don't miss when a job is "skipped". It looks like there isn't a way to mark the parent job as required, so I've just removed the requirement. We can mark the child jobs as required later, after this gets merged.

Also, the job being marked as "skipped" and not "failed" might be due to something in our workflow rather than an unsolvable GitHub actions issue, but I didn't want to put in the time to investigate that right now. Just something to keep in mind for the future.

2023-10-19 15:17 UTC, sam-golioth approved these changes

2023-10-19 16:06 UTC, merged